version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_run:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: node api/server.js